### ISSUE TITLE
❓ Is there any difference between easy/medium/hard for CNN_DM dataset

### ISSUE THREAD

**Issue by astariul-colanim** [microsoft/glge#4]
I downloaded the dataset and found out that `cnndm/test.src` is the same for all difficulty levels (`easy`, `medium`, `medium+`, `hard`).

**Why the results are different on the leaderboard ?**

**Comment by astariul-colanim** [comment]
Ha, I notice the amount of training data is different between each difficulty levels.

So if I want to evaluate an already trained model (on the full CNN_DM dataset) against GLGE benchmark, I can only do it for the `easy` level, right ?

**Comment by dayihengliu** [comment]
Yes, you can only do it on an easy level.
